### ISSUE TITLE
コードが良くない

### ISSUE THREAD

**Issue by imonikai** [imonikai/NU-EX2#4]
forの中身がデカすぎるような気がする。

関数名が何をする関数なのか具体的じゃない。

設定によって処理を行うかどうかをgradesは関数の中で、attendanceは関数呼び出しのところで判定していて、コードがわかりにくい。合否の強調表示はgradesの一部の機能だから今の状況になっている。関数を細かく分けるべきだと思う。

**Comment by Imonikai** [comment]
プログラミングの良し悪しは分からないけどとにかく良くない

**Comment by Imonikai** [comment]
リファクタリングをしてみたー。拡張機能はimportとかexportとか使えないっぽいからあんまり上手くできなかったけど、少しは良くなったと俺が信じなきゃ誰が俺を信じるんだい？
